apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ops-agents.fullname" . }}-config
  labels:
    {{- include "ops-agents.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.env.common }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}

