apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ops-agents.fullname" . }}-secrets
  labels:
    {{- include "ops-agents.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{- if ne $value "" }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
  {{- end }}

