{{- if and .Values.prometheus.enabled .Values.prometheus.serviceMonitor }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "ops-agents.fullname" . }}-gateway
  namespace: {{ .Values.prometheus.namespace | default .Release.Namespace }}
  labels:
    {{- include "ops-agents.gateway.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
spec:
  selector:
    matchLabels:
      {{- include "ops-agents.gateway.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_name]
          targetLabel: pod
        - sourceLabels: [__meta_kubernetes_namespace]
          targetLabel: namespace
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "ops-agents.fullname" . }}-orchestrator
  namespace: {{ .Values.prometheus.namespace | default .Release.Namespace }}
  labels:
    {{- include "ops-agents.orchestrator.labels" . | nindent 4 }}
    app.kubernetes.io/component: orchestrator
spec:
  selector:
    matchLabels:
      {{- include "ops-agents.orchestrator.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_name]
          targetLabel: pod
        - sourceLabels: [__meta_kubernetes_namespace]
          targetLabel: namespace
{{- end }}

